   name: Auto Generate Log
   on: [push]  # 触发条件：代码推送时运行[[3, 7]]

   jobs:
     deploy:
       runs-on: ubuntu-latest  # 使用GitHub提供的Linux环境[[17]]
       steps:
         - name: Checkout code
           uses: actions/checkout@v4  # 检出仓库代码[[16]]

         - name: SSH to Server & Create Log
           uses: appleboy/ssh-action@v1.0.0  # 使用SSH连接服务器的Action[[2]]
           with:
             host: ${{ secrets.SSH_HOST }}
             username: ${{ secrets.SSH_USER }}
             key: ${{ secrets.SSH_PRIVATE_KEY }}
             script: |
               # 生成以时间戳命名的日志文件（格式示例：20250227123045.log）
               TIMESTAMP=$(date +"%Y%m%d%H%M%S")
               touch /tmp/${TIMESTAMP}.log
               echo "New code pushed at $(date)" >> /tmp/${TIMESTAMP}.log

